export interface Currency {
  code: string;
  name: string;
  symbol: string;
  locale: string;
}

export const CURRENCIES: Currency[] = [
  { code: "DZ", name: "Algeria", symbol: "DZD", locale: "ar-DZ" },
  { code: "AR", name: "Argentina", symbol: "ARS", locale: "es-AR" },
  { code: "AU", name: "Australia", symbol: "AUD", locale: "en-AU" },
  { code: "BH", name: "Bahrain", symbol: "BHD", locale: "ar-BH" },
  { code: "BD", name: "Bangladesh", symbol: "BDT", locale: "bn-BD" },
  { code: "BO", name: "Bolivia", symbol: "BOB", locale: "es-BO" },
  { code: "BR", name: "Brazil", symbol: "BRL", locale: "pt-BR" },
  { code: "BG", name: "Bulgaria", symbol: "BGN", locale: "bg-BG" },
  { code: "KH", name: "Cambodia", symbol: "KHR", locale: "km-KH" },
  { code: "CM", name: "Cameroon", symbol: "XAF", locale: "fr-CM" },
  { code: "CA", name: "Canada", symbol: "CAD", locale: "en-CA" },
  { code: "CL", name: "Chile", symbol: "CLP", locale: "es-CL" },
  { code: "CN", name: "China", symbol: "CNY", locale: "zh-CN" },
  { code: "CO", name: "Colombia", symbol: "COP", locale: "es-CO" },
  { code: "CR", name: "Costa Rica", symbol: "CRC", locale: "es-CR" },
  { code: "HR", name: "Croatia", symbol: "EUR", locale: "hr-HR" },
  { code: "CZ", name: "Czech Republic", symbol: "CZK", locale: "cs-CZ" },
  { code: "DK", name: "Denmark", symbol: "DKK", locale: "da-DK" },
  { code: "DO", name: "Dominican Rep.", symbol: "DOP", locale: "es-DO" },
  { code: "EC", name: "Ecuador", symbol: "USD", locale: "es-EC" },
  { code: "EG", name: "Egypt", symbol: "EGP", locale: "ar-EG" },
  { code: "ET", name: "Ethiopia", symbol: "ETB", locale: "am-ET" },
  { code: "EU", name: "Europe (EUR)", symbol: "EUR", locale: "de-DE" },
  { code: "FJ", name: "Fiji", symbol: "FJD", locale: "en-FJ" },
  { code: "GE", name: "Georgia", symbol: "GEL", locale: "ka-GE" },
  { code: "GH", name: "Ghana", symbol: "GHS", locale: "en-GH" },
  { code: "GT", name: "Guatemala", symbol: "GTQ", locale: "es-GT" },
  { code: "HK", name: "Hong Kong", symbol: "HKD", locale: "en-HK" },
  { code: "HU", name: "Hungary", symbol: "HUF", locale: "hu-HU" },
  { code: "IS", name: "Iceland", symbol: "ISK", locale: "is-IS" },
  { code: "IN", name: "India", symbol: "INR", locale: "en-IN" },
  { code: "ID", name: "Indonesia", symbol: "IDR", locale: "id-ID" },
  { code: "IR", name: "Iran", symbol: "IRR", locale: "fa-IR" },
  { code: "IQ", name: "Iraq", symbol: "IQD", locale: "ar-IQ" },
  { code: "IL", name: "Israel", symbol: "ILS", locale: "he-IL" },
  { code: "CI", name: "Ivory Coast", symbol: "XOF", locale: "fr-CI" },
  { code: "JM", name: "Jamaica", symbol: "JMD", locale: "en-JM" },
  { code: "JP", name: "Japan", symbol: "JPY", locale: "ja-JP" },
  { code: "JO", name: "Jordan", symbol: "JOD", locale: "ar-JO" },
  { code: "KE", name: "Kenya", symbol: "KES", locale: "en-KE" },
  { code: "KW", name: "Kuwait", symbol: "KWD", locale: "ar-KW" },
  { code: "LA", name: "Laos", symbol: "LAK", locale: "lo-LA" },
  { code: "LB", name: "Lebanon", symbol: "LBP", locale: "ar-LB" },
  { code: "MY", name: "Malaysia", symbol: "MYR", locale: "ms-MY" },
  { code: "MU", name: "Mauritius", symbol: "MUR", locale: "en-MU" },
  { code: "MX", name: "Mexico", symbol: "MXN", locale: "es-MX" },
  { code: "MN", name: "Mongolia", symbol: "MNT", locale: "mn-MN" },
  { code: "MA", name: "Morocco", symbol: "MAD", locale: "ar-MA" },
  { code: "MM", name: "Myanmar", symbol: "MMK", locale: "my-MM" },
  { code: "NP", name: "Nepal", symbol: "NPR", locale: "ne-NP" },
  { code: "NZ", name: "New Zealand", symbol: "NZD", locale: "en-NZ" },
  { code: "NG", name: "Nigeria", symbol: "NGN", locale: "en-NG" },
  { code: "NO", name: "Norway", symbol: "NOK", locale: "nb-NO" },
  { code: "OM", name: "Oman", symbol: "OMR", locale: "ar-OM" },
  { code: "PK", name: "Pakistan", symbol: "PKR", locale: "en-PK" },
  { code: "PA", name: "Panama", symbol: "PAB", locale: "es-PA" },
  { code: "PY", name: "Paraguay", symbol: "PYG", locale: "es-PY" },
  { code: "PE", name: "Peru", symbol: "PEN", locale: "es-PE" },
  { code: "PH", name: "Philippines", symbol: "PHP", locale: "en-PH" },
  { code: "PL", name: "Poland", symbol: "PLN", locale: "pl-PL" },
  { code: "QA", name: "Qatar", symbol: "QAR", locale: "ar-QA" },
  { code: "RO", name: "Romania", symbol: "RON", locale: "ro-RO" },
  { code: "RU", name: "Russia", symbol: "RUB", locale: "ru-RU" },
  { code: "RW", name: "Rwanda", symbol: "RWF", locale: "rw-RW" },
  { code: "SA", name: "Saudi Arabia", symbol: "SAR", locale: "ar-SA" },
  { code: "SN", name: "Senegal", symbol: "XOF", locale: "fr-SN" },
  { code: "RS", name: "Serbia", symbol: "RSD", locale: "sr-RS" },
  { code: "SG", name: "Singapore", symbol: "SGD", locale: "en-SG" },
  { code: "ZA", name: "South Africa", symbol: "ZAR", locale: "en-ZA" },
  { code: "KR", name: "South Korea", symbol: "KRW", locale: "ko-KR" },
  { code: "LK", name: "Sri Lanka", symbol: "LKR", locale: "si-LK" },
  { code: "SE", name: "Sweden", symbol: "SEK", locale: "sv-SE" },
  { code: "CH", name: "Switzerland", symbol: "CHF", locale: "de-CH" },
  { code: "TW", name: "Taiwan", symbol: "TWD", locale: "zh-TW" },
  { code: "TZ", name: "Tanzania", symbol: "TZS", locale: "sw-TZ" },
  { code: "TH", name: "Thailand", symbol: "THB", locale: "th-TH" },
  { code: "TT", name: "Trinidad & Tobago", symbol: "TTD", locale: "en-TT" },
  { code: "TN", name: "Tunisia", symbol: "TND", locale: "ar-TN" },
  { code: "TR", name: "Turkey", symbol: "TRY", locale: "tr-TR" },
  { code: "AE", name: "UAE", symbol: "AED", locale: "ar-AE" },
  { code: "UG", name: "Uganda", symbol: "UGX", locale: "en-UG" },
  { code: "UA", name: "Ukraine", symbol: "UAH", locale: "uk-UA" },
  { code: "GB", name: "United Kingdom", symbol: "GBP", locale: "en-GB" },
  { code: "US", name: "United States", symbol: "USD", locale: "en-US" },
  { code: "UY", name: "Uruguay", symbol: "UYU", locale: "es-UY" },
  { code: "VE", name: "Venezuela", symbol: "VES", locale: "es-VE" },
  { code: "VN", name: "Vietnam", symbol: "VND", locale: "vi-VN" },
];
