export interface EmojiItem {
  emoji: string;
  name: string;
  category: string;
}

export const EMOJI_CATEGORIES = [
  "Smileys",
  "People",
  "Nature",
  "Food",
  "Activities",
  "Travel",
  "Objects",
  "Symbols",
] as const;

export const EMOJIS: EmojiItem[] = [
  // Smileys
  { emoji: "😀", name: "grinning face", category: "Smileys" },
  { emoji: "😃", name: "grinning face with big eyes", category: "Smileys" },
  { emoji: "😄", name: "grinning face with smiling eyes", category: "Smileys" },
  { emoji: "😁", name: "beaming face", category: "Smileys" },
  { emoji: "😆", name: "grinning squinting face", category: "Smileys" },
  { emoji: "😅", name: "grinning face with sweat", category: "Smileys" },
  { emoji: "🤣", name: "rolling on the floor laughing", category: "Smileys" },
  { emoji: "😂", name: "face with tears of joy", category: "Smileys" },
  { emoji: "🙂", name: "slightly smiling face", category: "Smileys" },
  { emoji: "😊", name: "smiling face with smiling eyes", category: "Smileys" },
  { emoji: "😇", name: "smiling face with halo", category: "Smileys" },
  { emoji: "🥰", name: "smiling face with hearts", category: "Smileys" },
  { emoji: "😍", name: "smiling face with heart eyes", category: "Smileys" },
  { emoji: "🤩", name: "star struck", category: "Smileys" },
  { emoji: "😘", name: "face blowing a kiss", category: "Smileys" },
  { emoji: "😋", name: "face savoring food", category: "Smileys" },
  { emoji: "😜", name: "winking face with tongue", category: "Smileys" },
  { emoji: "🤪", name: "zany face", category: "Smileys" },
  { emoji: "😎", name: "smiling face with sunglasses", category: "Smileys" },
  { emoji: "🤓", name: "nerd face", category: "Smileys" },
  { emoji: "🧐", name: "face with monocle", category: "Smileys" },
  { emoji: "🤔", name: "thinking face", category: "Smileys" },
  { emoji: "🤗", name: "hugging face", category: "Smileys" },
  { emoji: "😐", name: "neutral face", category: "Smileys" },
  { emoji: "😑", name: "expressionless face", category: "Smileys" },
  { emoji: "😶", name: "face without mouth", category: "Smileys" },
  { emoji: "🙄", name: "face with rolling eyes", category: "Smileys" },
  { emoji: "😏", name: "smirking face", category: "Smileys" },
  { emoji: "😬", name: "grimacing face", category: "Smileys" },
  { emoji: "😮‍💨", name: "face exhaling", category: "Smileys" },
  { emoji: "🤥", name: "lying face", category: "Smileys" },
  { emoji: "😌", name: "relieved face", category: "Smileys" },
  { emoji: "😔", name: "pensive face", category: "Smileys" },
  { emoji: "😪", name: "sleepy face", category: "Smileys" },
  { emoji: "🤤", name: "drooling face", category: "Smileys" },
  { emoji: "😴", name: "sleeping face", category: "Smileys" },
  { emoji: "😷", name: "face with medical mask", category: "Smileys" },
  { emoji: "🤒", name: "face with thermometer", category: "Smileys" },
  { emoji: "🤕", name: "face with head bandage", category: "Smileys" },
  { emoji: "🤢", name: "nauseated face", category: "Smileys" },
  { emoji: "🤮", name: "face vomiting", category: "Smileys" },
  { emoji: "🥵", name: "hot face", category: "Smileys" },
  { emoji: "🥶", name: "cold face", category: "Smileys" },
  { emoji: "😵", name: "face with crossed out eyes", category: "Smileys" },
  { emoji: "🤯", name: "exploding head", category: "Smileys" },
  { emoji: "🥳", name: "partying face", category: "Smileys" },
  { emoji: "🥺", name: "pleading face", category: "Smileys" },
  { emoji: "😢", name: "crying face", category: "Smileys" },
  { emoji: "😭", name: "loudly crying face", category: "Smileys" },
  { emoji: "😤", name: "face with steam from nose", category: "Smileys" },
  { emoji: "😠", name: "angry face", category: "Smileys" },
  { emoji: "🤬", name: "face with symbols on mouth", category: "Smileys" },
  { emoji: "😈", name: "smiling face with horns", category: "Smileys" },
  { emoji: "💀", name: "skull", category: "Smileys" },
  { emoji: "💩", name: "pile of poo", category: "Smileys" },
  { emoji: "🤡", name: "clown face", category: "Smileys" },
  { emoji: "👻", name: "ghost", category: "Smileys" },
  { emoji: "👽", name: "alien", category: "Smileys" },
  { emoji: "🤖", name: "robot", category: "Smileys" },
  { emoji: "🎃", name: "jack o lantern", category: "Smileys" },

  // People
  { emoji: "👋", name: "waving hand", category: "People" },
  { emoji: "🤚", name: "raised back of hand", category: "People" },
  { emoji: "✋", name: "raised hand", category: "People" },
  { emoji: "🖖", name: "vulcan salute", category: "People" },
  { emoji: "👌", name: "ok hand", category: "People" },
  { emoji: "🤌", name: "pinched fingers", category: "People" },
  { emoji: "🤏", name: "pinching hand", category: "People" },
  { emoji: "✌️", name: "victory hand", category: "People" },
  { emoji: "🤞", name: "crossed fingers", category: "People" },
  { emoji: "🫰", name: "hand with index finger and thumb crossed", category: "People" },
  { emoji: "🤟", name: "love you gesture", category: "People" },
  { emoji: "🤘", name: "sign of the horns", category: "People" },
  { emoji: "🤙", name: "call me hand", category: "People" },
  { emoji: "👈", name: "backhand index pointing left", category: "People" },
  { emoji: "👉", name: "backhand index pointing right", category: "People" },
  { emoji: "👆", name: "backhand index pointing up", category: "People" },
  { emoji: "👇", name: "backhand index pointing down", category: "People" },
  { emoji: "☝️", name: "index pointing up", category: "People" },
  { emoji: "🫵", name: "index pointing at the viewer", category: "People" },
  { emoji: "👍", name: "thumbs up", category: "People" },
  { emoji: "👎", name: "thumbs down", category: "People" },
  { emoji: "✊", name: "raised fist", category: "People" },
  { emoji: "👊", name: "oncoming fist", category: "People" },
  { emoji: "🤛", name: "left facing fist", category: "People" },
  { emoji: "🤜", name: "right facing fist", category: "People" },
  { emoji: "👏", name: "clapping hands", category: "People" },
  { emoji: "🙌", name: "raising hands", category: "People" },
  { emoji: "🫶", name: "heart hands", category: "People" },
  { emoji: "👐", name: "open hands", category: "People" },
  { emoji: "🤝", name: "handshake", category: "People" },
  { emoji: "🙏", name: "folded hands", category: "People" },
  { emoji: "💪", name: "flexed biceps", category: "People" },
  { emoji: "🦾", name: "mechanical arm", category: "People" },
  { emoji: "🖐️", name: "hand with fingers splayed", category: "People" },
  { emoji: "👀", name: "eyes", category: "People" },
  { emoji: "👁️", name: "eye", category: "People" },
  { emoji: "👅", name: "tongue", category: "People" },
  { emoji: "👄", name: "mouth", category: "People" },
  { emoji: "🧠", name: "brain", category: "People" },
  { emoji: "👶", name: "baby", category: "People" },
  { emoji: "👧", name: "girl", category: "People" },
  { emoji: "👦", name: "boy", category: "People" },
  { emoji: "👩", name: "woman", category: "People" },
  { emoji: "👨", name: "man", category: "People" },
  { emoji: "👴", name: "old man", category: "People" },
  { emoji: "👵", name: "old woman", category: "People" },
  { emoji: "👨‍💻", name: "man technologist", category: "People" },
  { emoji: "👩‍💻", name: "woman technologist", category: "People" },
  { emoji: "👨‍🍳", name: "man cook", category: "People" },
  { emoji: "👩‍🍳", name: "woman cook", category: "People" },
  { emoji: "👨‍🎓", name: "man student", category: "People" },
  { emoji: "👩‍🎓", name: "woman student", category: "People" },
  { emoji: "👨‍💼", name: "man office worker", category: "People" },
  { emoji: "👩‍💼", name: "woman office worker", category: "People" },
  { emoji: "👨‍🔧", name: "man mechanic", category: "People" },
  { emoji: "👩‍⚕️", name: "woman health worker", category: "People" },
  { emoji: "👨‍👩‍👧", name: "family", category: "People" },
  { emoji: "🧑‍🤝‍🧑", name: "people holding hands", category: "People" },

  // Nature
  { emoji: "🐶", name: "dog face", category: "Nature" },
  { emoji: "🐕", name: "dog", category: "Nature" },
  { emoji: "🐱", name: "cat face", category: "Nature" },
  { emoji: "🐈", name: "cat", category: "Nature" },
  { emoji: "🐭", name: "mouse face", category: "Nature" },
  { emoji: "🐹", name: "hamster", category: "Nature" },
  { emoji: "🐰", name: "rabbit face", category: "Nature" },
  { emoji: "🦊", name: "fox", category: "Nature" },
  { emoji: "🐻", name: "bear", category: "Nature" },
  { emoji: "🐼", name: "panda", category: "Nature" },
  { emoji: "🐨", name: "koala", category: "Nature" },
  { emoji: "🐯", name: "tiger face", category: "Nature" },
  { emoji: "🦁", name: "lion", category: "Nature" },
  { emoji: "🐮", name: "cow face", category: "Nature" },
  { emoji: "🐷", name: "pig face", category: "Nature" },
  { emoji: "🐸", name: "frog", category: "Nature" },
  { emoji: "🐵", name: "monkey face", category: "Nature" },
  { emoji: "🙈", name: "see no evil monkey", category: "Nature" },
  { emoji: "🙉", name: "hear no evil monkey", category: "Nature" },
  { emoji: "🙊", name: "speak no evil monkey", category: "Nature" },
  { emoji: "🐔", name: "chicken", category: "Nature" },
  { emoji: "🐧", name: "penguin", category: "Nature" },
  { emoji: "🐦", name: "bird", category: "Nature" },
  { emoji: "🦅", name: "eagle", category: "Nature" },
  { emoji: "🦆", name: "duck", category: "Nature" },
  { emoji: "🦉", name: "owl", category: "Nature" },
  { emoji: "🐝", name: "honeybee", category: "Nature" },
  { emoji: "🪲", name: "beetle", category: "Nature" },
  { emoji: "🐛", name: "bug", category: "Nature" },
  { emoji: "🦋", name: "butterfly", category: "Nature" },
  { emoji: "🐌", name: "snail", category: "Nature" },
  { emoji: "🐙", name: "octopus", category: "Nature" },
  { emoji: "🐠", name: "tropical fish", category: "Nature" },
  { emoji: "🐬", name: "dolphin", category: "Nature" },
  { emoji: "🐳", name: "spouting whale", category: "Nature" },
  { emoji: "🦈", name: "shark", category: "Nature" },
  { emoji: "🐊", name: "crocodile", category: "Nature" },
  { emoji: "🐘", name: "elephant", category: "Nature" },
  { emoji: "🦒", name: "giraffe", category: "Nature" },
  { emoji: "🦓", name: "zebra", category: "Nature" },
  { emoji: "🐎", name: "horse", category: "Nature" },
  { emoji: "🦄", name: "unicorn", category: "Nature" },
  { emoji: "🐉", name: "dragon", category: "Nature" },
  { emoji: "🌸", name: "cherry blossom", category: "Nature" },
  { emoji: "🌹", name: "rose", category: "Nature" },
  { emoji: "🌺", name: "hibiscus", category: "Nature" },
  { emoji: "🌻", name: "sunflower", category: "Nature" },
  { emoji: "🌷", name: "tulip", category: "Nature" },
  { emoji: "🌱", name: "seedling", category: "Nature" },
  { emoji: "🌲", name: "evergreen tree", category: "Nature" },
  { emoji: "🌳", name: "deciduous tree", category: "Nature" },
  { emoji: "🌴", name: "palm tree", category: "Nature" },
  { emoji: "🌵", name: "cactus", category: "Nature" },
  { emoji: "🍀", name: "four leaf clover", category: "Nature" },
  { emoji: "🍁", name: "maple leaf", category: "Nature" },
  { emoji: "🍂", name: "fallen leaf", category: "Nature" },
  { emoji: "🍃", name: "leaf fluttering in wind", category: "Nature" },
  { emoji: "🌊", name: "water wave", category: "Nature" },
  { emoji: "☀️", name: "sun", category: "Nature" },
  { emoji: "🌙", name: "crescent moon", category: "Nature" },
  { emoji: "⭐", name: "star", category: "Nature" },
  { emoji: "🌟", name: "glowing star", category: "Nature" },
  { emoji: "🔥", name: "fire", category: "Nature" },
  { emoji: "❄️", name: "snowflake", category: "Nature" },
  { emoji: "🌈", name: "rainbow", category: "Nature" },
  { emoji: "⛅", name: "sun behind cloud", category: "Nature" },
  { emoji: "🌧️", name: "cloud with rain", category: "Nature" },
  { emoji: "⛈️", name: "cloud with lightning and rain", category: "Nature" },
  { emoji: "🌪️", name: "tornado", category: "Nature" },

  // Food
  { emoji: "🍎", name: "red apple", category: "Food" },
  { emoji: "🍊", name: "tangerine", category: "Food" },
  { emoji: "🍋", name: "lemon", category: "Food" },
  { emoji: "🍌", name: "banana", category: "Food" },
  { emoji: "🍉", name: "watermelon", category: "Food" },
  { emoji: "🍇", name: "grapes", category: "Food" },
  { emoji: "🍓", name: "strawberry", category: "Food" },
  { emoji: "🫐", name: "blueberries", category: "Food" },
  { emoji: "🍑", name: "peach", category: "Food" },
  { emoji: "🥭", name: "mango", category: "Food" },
  { emoji: "🍍", name: "pineapple", category: "Food" },
  { emoji: "🥥", name: "coconut", category: "Food" },
  { emoji: "🥑", name: "avocado", category: "Food" },
  { emoji: "🍆", name: "eggplant", category: "Food" },
  { emoji: "🥦", name: "broccoli", category: "Food" },
  { emoji: "🥕", name: "carrot", category: "Food" },
  { emoji: "🌽", name: "ear of corn", category: "Food" },
  { emoji: "🌶️", name: "hot pepper", category: "Food" },
  { emoji: "🧄", name: "garlic", category: "Food" },
  { emoji: "🧅", name: "onion", category: "Food" },
  { emoji: "🥐", name: "croissant", category: "Food" },
  { emoji: "🍞", name: "bread", category: "Food" },
  { emoji: "🥖", name: "baguette", category: "Food" },
  { emoji: "🥞", name: "pancakes", category: "Food" },
  { emoji: "🧇", name: "waffle", category: "Food" },
  { emoji: "🍳", name: "cooking", category: "Food" },
  { emoji: "🥚", name: "egg", category: "Food" },
  { emoji: "🧈", name: "butter", category: "Food" },
  { emoji: "🥓", name: "bacon", category: "Food" },
  { emoji: "🥩", name: "cut of meat", category: "Food" },
  { emoji: "🍗", name: "poultry leg", category: "Food" },
  { emoji: "🌭", name: "hot dog", category: "Food" },
  { emoji: "🍔", name: "hamburger", category: "Food" },
  { emoji: "🍟", name: "french fries", category: "Food" },
  { emoji: "🍕", name: "pizza", category: "Food" },
  { emoji: "🌮", name: "taco", category: "Food" },
  { emoji: "🌯", name: "burrito", category: "Food" },
  { emoji: "🥗", name: "green salad", category: "Food" },
  { emoji: "🍜", name: "steaming bowl", category: "Food" },
  { emoji: "🍝", name: "spaghetti", category: "Food" },
  { emoji: "🍣", name: "sushi", category: "Food" },
  { emoji: "🍱", name: "bento box", category: "Food" },
  { emoji: "🥟", name: "dumpling", category: "Food" },
  { emoji: "🍚", name: "cooked rice", category: "Food" },
  { emoji: "🍛", name: "curry rice", category: "Food" },
  { emoji: "🍦", name: "ice cream", category: "Food" },
  { emoji: "🍧", name: "shaved ice", category: "Food" },
  { emoji: "🍩", name: "doughnut", category: "Food" },
  { emoji: "🍪", name: "cookie", category: "Food" },
  { emoji: "🎂", name: "birthday cake", category: "Food" },
  { emoji: "🍰", name: "shortcake", category: "Food" },
  { emoji: "🧁", name: "cupcake", category: "Food" },
  { emoji: "🍫", name: "chocolate bar", category: "Food" },
  { emoji: "🍬", name: "candy", category: "Food" },
  { emoji: "🍭", name: "lollipop", category: "Food" },
  { emoji: "☕", name: "coffee", category: "Food" },
  { emoji: "🍵", name: "teacup", category: "Food" },
  { emoji: "🧋", name: "bubble tea", category: "Food" },
  { emoji: "🥤", name: "cup with straw", category: "Food" },
  { emoji: "🧃", name: "juice box", category: "Food" },
  { emoji: "🍺", name: "beer mug", category: "Food" },
  { emoji: "🍷", name: "wine glass", category: "Food" },
  { emoji: "🥂", name: "clinking glasses", category: "Food" },
  { emoji: "🍸", name: "cocktail glass", category: "Food" },
  { emoji: "🍹", name: "tropical drink", category: "Food" },
  { emoji: "🥡", name: "takeout box", category: "Food" },

  // Activities
  { emoji: "⚽", name: "soccer ball", category: "Activities" },
  { emoji: "🏀", name: "basketball", category: "Activities" },
  { emoji: "🏈", name: "american football", category: "Activities" },
  { emoji: "⚾", name: "baseball", category: "Activities" },
  { emoji: "🥎", name: "softball", category: "Activities" },
  { emoji: "🎾", name: "tennis", category: "Activities" },
  { emoji: "🏐", name: "volleyball", category: "Activities" },
  { emoji: "🏉", name: "rugby football", category: "Activities" },
  { emoji: "🎱", name: "pool 8 ball", category: "Activities" },
  { emoji: "🏓", name: "ping pong", category: "Activities" },
  { emoji: "🏸", name: "badminton", category: "Activities" },
  { emoji: "🥊", name: "boxing glove", category: "Activities" },
  { emoji: "⛳", name: "flag in hole", category: "Activities" },
  { emoji: "🏋️", name: "person lifting weights", category: "Activities" },
  { emoji: "🧘", name: "person in lotus position", category: "Activities" },
  { emoji: "🚴", name: "person biking", category: "Activities" },
  { emoji: "🏊", name: "person swimming", category: "Activities" },
  { emoji: "🏄", name: "person surfing", category: "Activities" },
  { emoji: "🧗", name: "person climbing", category: "Activities" },
  { emoji: "⛷️", name: "skier", category: "Activities" },
  { emoji: "🏂", name: "snowboarder", category: "Activities" },
  { emoji: "🎮", name: "video game", category: "Activities" },
  { emoji: "🕹️", name: "joystick", category: "Activities" },
  { emoji: "🎲", name: "game die", category: "Activities" },
  { emoji: "♟️", name: "chess pawn", category: "Activities" },
  { emoji: "🧩", name: "puzzle piece", category: "Activities" },
  { emoji: "🎬", name: "clapper board", category: "Activities" },
  { emoji: "🎵", name: "musical note", category: "Activities" },
  { emoji: "🎶", name: "musical notes", category: "Activities" },
  { emoji: "🎧", name: "headphone", category: "Activities" },
  { emoji: "🎤", name: "microphone", category: "Activities" },
  { emoji: "🎸", name: "guitar", category: "Activities" },
  { emoji: "🎹", name: "musical keyboard", category: "Activities" },
  { emoji: "🥁", name: "drum", category: "Activities" },
  { emoji: "🎺", name: "trumpet", category: "Activities" },
  { emoji: "🎻", name: "violin", category: "Activities" },
  { emoji: "🎨", name: "artist palette", category: "Activities" },
  { emoji: "🖌️", name: "paintbrush", category: "Activities" },
  { emoji: "📺", name: "television", category: "Activities" },
  { emoji: "📸", name: "camera with flash", category: "Activities" },
  { emoji: "📷", name: "camera", category: "Activities" },
  { emoji: "🎯", name: "bullseye", category: "Activities" },
  { emoji: "🎪", name: "circus tent", category: "Activities" },
  { emoji: "🎭", name: "performing arts", category: "Activities" },
  { emoji: "🎰", name: "slot machine", category: "Activities" },
  { emoji: "🏆", name: "trophy", category: "Activities" },
  { emoji: "🥇", name: "gold medal", category: "Activities" },
  { emoji: "🥈", name: "silver medal", category: "Activities" },
  { emoji: "🥉", name: "bronze medal", category: "Activities" },
  { emoji: "🎖️", name: "military medal", category: "Activities" },

  // Travel
  { emoji: "🚗", name: "car", category: "Travel" },
  { emoji: "🚕", name: "taxi", category: "Travel" },
  { emoji: "🚙", name: "sport utility vehicle", category: "Travel" },
  { emoji: "🚌", name: "bus", category: "Travel" },
  { emoji: "🚎", name: "trolleybus", category: "Travel" },
  { emoji: "🚐", name: "minibus", category: "Travel" },
  { emoji: "🚑", name: "ambulance", category: "Travel" },
  { emoji: "🚒", name: "fire engine", category: "Travel" },
  { emoji: "🚓", name: "police car", category: "Travel" },
  { emoji: "🛻", name: "pickup truck", category: "Travel" },
  { emoji: "🚚", name: "delivery truck", category: "Travel" },
  { emoji: "🏎️", name: "racing car", category: "Travel" },
  { emoji: "🏍️", name: "motorcycle", category: "Travel" },
  { emoji: "🛵", name: "motor scooter", category: "Travel" },
  { emoji: "🚲", name: "bicycle", category: "Travel" },
  { emoji: "🛴", name: "kick scooter", category: "Travel" },
  { emoji: "🚂", name: "locomotive", category: "Travel" },
  { emoji: "🚆", name: "train", category: "Travel" },
  { emoji: "🚇", name: "metro", category: "Travel" },
  { emoji: "✈️", name: "airplane", category: "Travel" },
  { emoji: "🚀", name: "rocket", category: "Travel" },
  { emoji: "🛸", name: "flying saucer", category: "Travel" },
  { emoji: "🚁", name: "helicopter", category: "Travel" },
  { emoji: "⛵", name: "sailboat", category: "Travel" },
  { emoji: "🚢", name: "ship", category: "Travel" },
  { emoji: "⛽", name: "fuel pump", category: "Travel" },
  { emoji: "🏠", name: "house", category: "Travel" },
  { emoji: "🏡", name: "house with garden", category: "Travel" },
  { emoji: "🏢", name: "office building", category: "Travel" },
  { emoji: "🏣", name: "post office", category: "Travel" },
  { emoji: "🏥", name: "hospital", category: "Travel" },
  { emoji: "🏦", name: "bank", category: "Travel" },
  { emoji: "🏨", name: "hotel", category: "Travel" },
  { emoji: "🏩", name: "love hotel", category: "Travel" },
  { emoji: "🏪", name: "convenience store", category: "Travel" },
  { emoji: "🏫", name: "school", category: "Travel" },
  { emoji: "🏬", name: "department store", category: "Travel" },
  { emoji: "🏭", name: "factory", category: "Travel" },
  { emoji: "🏯", name: "japanese castle", category: "Travel" },
  { emoji: "🏰", name: "castle", category: "Travel" },
  { emoji: "⛪", name: "church", category: "Travel" },
  { emoji: "🕌", name: "mosque", category: "Travel" },
  { emoji: "🗼", name: "tokyo tower", category: "Travel" },
  { emoji: "🗽", name: "statue of liberty", category: "Travel" },
  { emoji: "🗺️", name: "world map", category: "Travel" },
  { emoji: "🧭", name: "compass", category: "Travel" },
  { emoji: "🏖️", name: "beach with umbrella", category: "Travel" },
  { emoji: "🏔️", name: "snow capped mountain", category: "Travel" },
  { emoji: "⛰️", name: "mountain", category: "Travel" },
  { emoji: "🌋", name: "volcano", category: "Travel" },
  { emoji: "🏕️", name: "camping", category: "Travel" },

  // Objects
  { emoji: "⌚", name: "watch", category: "Objects" },
  { emoji: "📱", name: "mobile phone", category: "Objects" },
  { emoji: "📲", name: "mobile phone with arrow", category: "Objects" },
  { emoji: "💻", name: "laptop", category: "Objects" },
  { emoji: "🖥️", name: "desktop computer", category: "Objects" },
  { emoji: "🖨️", name: "printer", category: "Objects" },
  { emoji: "⌨️", name: "keyboard", category: "Objects" },
  { emoji: "🖱️", name: "computer mouse", category: "Objects" },
  { emoji: "💾", name: "floppy disk", category: "Objects" },
  { emoji: "💿", name: "optical disk", category: "Objects" },
  { emoji: "🎥", name: "movie camera", category: "Objects" },
  { emoji: "📞", name: "telephone receiver", category: "Objects" },
  { emoji: "📟", name: "pager", category: "Objects" },
  { emoji: "📠", name: "fax machine", category: "Objects" },
  { emoji: "📧", name: "email", category: "Objects" },
  { emoji: "📨", name: "incoming envelope", category: "Objects" },
  { emoji: "📩", name: "envelope with arrow", category: "Objects" },
  { emoji: "📮", name: "postbox", category: "Objects" },
  { emoji: "📦", name: "package", category: "Objects" },
  { emoji: "📋", name: "clipboard", category: "Objects" },
  { emoji: "📝", name: "memo", category: "Objects" },
  { emoji: "📁", name: "file folder", category: "Objects" },
  { emoji: "📂", name: "open file folder", category: "Objects" },
  { emoji: "📅", name: "calendar", category: "Objects" },
  { emoji: "📆", name: "tear off calendar", category: "Objects" },
  { emoji: "📇", name: "card index", category: "Objects" },
  { emoji: "📈", name: "chart increasing", category: "Objects" },
  { emoji: "📉", name: "chart decreasing", category: "Objects" },
  { emoji: "📊", name: "bar chart", category: "Objects" },
  { emoji: "📌", name: "pushpin", category: "Objects" },
  { emoji: "📎", name: "paperclip", category: "Objects" },
  { emoji: "📏", name: "straight ruler", category: "Objects" },
  { emoji: "✂️", name: "scissors", category: "Objects" },
  { emoji: "🔒", name: "locked", category: "Objects" },
  { emoji: "🔓", name: "unlocked", category: "Objects" },
  { emoji: "🔑", name: "key", category: "Objects" },
  { emoji: "🗝️", name: "old key", category: "Objects" },
  { emoji: "🔧", name: "wrench", category: "Objects" },
  { emoji: "🔨", name: "hammer", category: "Objects" },
  { emoji: "🛠️", name: "hammer and wrench", category: "Objects" },
  { emoji: "⚙️", name: "gear", category: "Objects" },
  { emoji: "🔩", name: "nut and bolt", category: "Objects" },
  { emoji: "💳", name: "credit card", category: "Objects" },
  { emoji: "💰", name: "money bag", category: "Objects" },
  { emoji: "💵", name: "dollar banknote", category: "Objects" },
  { emoji: "💴", name: "yen banknote", category: "Objects" },
  { emoji: "💶", name: "euro banknote", category: "Objects" },
  { emoji: "💷", name: "pound banknote", category: "Objects" },
  { emoji: "💸", name: "money with wings", category: "Objects" },
  { emoji: "🪙", name: "coin", category: "Objects" },
  { emoji: "💡", name: "light bulb", category: "Objects" },
  { emoji: "🔦", name: "flashlight", category: "Objects" },
  { emoji: "🕯️", name: "candle", category: "Objects" },
  { emoji: "🧯", name: "fire extinguisher", category: "Objects" },
  { emoji: "🛒", name: "shopping cart", category: "Objects" },
  { emoji: "🛍️", name: "shopping bags", category: "Objects" },
  { emoji: "🎁", name: "wrapped gift", category: "Objects" },
  { emoji: "🏷️", name: "label", category: "Objects" },
  { emoji: "🧾", name: "receipt", category: "Objects" },
  { emoji: "💊", name: "pill", category: "Objects" },
  { emoji: "🩺", name: "stethoscope", category: "Objects" },
  { emoji: "💉", name: "syringe", category: "Objects" },
  { emoji: "🩹", name: "adhesive bandage", category: "Objects" },
  { emoji: "🛡️", name: "shield", category: "Objects" },
  { emoji: "⏰", name: "alarm clock", category: "Objects" },
  { emoji: "⏱️", name: "stopwatch", category: "Objects" },
  { emoji: "🔋", name: "battery", category: "Objects" },
  { emoji: "🔌", name: "electric plug", category: "Objects" },
  { emoji: "📡", name: "satellite antenna", category: "Objects" },
  { emoji: "🧲", name: "magnet", category: "Objects" },
  { emoji: "🪣", name: "bucket", category: "Objects" },
  { emoji: "🧰", name: "toolbox", category: "Objects" },
  { emoji: "📚", name: "books", category: "Objects" },
  { emoji: "📖", name: "open book", category: "Objects" },
  { emoji: "✏️", name: "pencil", category: "Objects" },
  { emoji: "🖊️", name: "pen", category: "Objects" },
  { emoji: "🖋️", name: "fountain pen", category: "Objects" },

  // Symbols
  { emoji: "❤️", name: "red heart", category: "Symbols" },
  { emoji: "🧡", name: "orange heart", category: "Symbols" },
  { emoji: "💛", name: "yellow heart", category: "Symbols" },
  { emoji: "💚", name: "green heart", category: "Symbols" },
  { emoji: "💙", name: "blue heart", category: "Symbols" },
  { emoji: "💜", name: "purple heart", category: "Symbols" },
  { emoji: "🖤", name: "black heart", category: "Symbols" },
  { emoji: "🤍", name: "white heart", category: "Symbols" },
  { emoji: "🤎", name: "brown heart", category: "Symbols" },
  { emoji: "💔", name: "broken heart", category: "Symbols" },
  { emoji: "❣️", name: "heart exclamation", category: "Symbols" },
  { emoji: "💕", name: "two hearts", category: "Symbols" },
  { emoji: "💞", name: "revolving hearts", category: "Symbols" },
  { emoji: "💓", name: "beating heart", category: "Symbols" },
  { emoji: "💗", name: "growing heart", category: "Symbols" },
  { emoji: "💖", name: "sparkling heart", category: "Symbols" },
  { emoji: "💘", name: "heart with arrow", category: "Symbols" },
  { emoji: "💝", name: "heart with ribbon", category: "Symbols" },
  { emoji: "⚡", name: "high voltage", category: "Symbols" },
  { emoji: "💥", name: "collision", category: "Symbols" },
  { emoji: "💫", name: "dizzy", category: "Symbols" },
  { emoji: "✨", name: "sparkles", category: "Symbols" },
  { emoji: "💢", name: "anger symbol", category: "Symbols" },
  { emoji: "💬", name: "speech balloon", category: "Symbols" },
  { emoji: "💭", name: "thought balloon", category: "Symbols" },
  { emoji: "🗯️", name: "right anger bubble", category: "Symbols" },
  { emoji: "✅", name: "check mark", category: "Symbols" },
  { emoji: "☑️", name: "check box with check", category: "Symbols" },
  { emoji: "❌", name: "cross mark", category: "Symbols" },
  { emoji: "❎", name: "cross mark button", category: "Symbols" },
  { emoji: "⭕", name: "hollow red circle", category: "Symbols" },
  { emoji: "🚫", name: "prohibited", category: "Symbols" },
  { emoji: "⛔", name: "no entry", category: "Symbols" },
  { emoji: "⚠️", name: "warning", category: "Symbols" },
  { emoji: "🔴", name: "red circle", category: "Symbols" },
  { emoji: "🟠", name: "orange circle", category: "Symbols" },
  { emoji: "🟡", name: "yellow circle", category: "Symbols" },
  { emoji: "🟢", name: "green circle", category: "Symbols" },
  { emoji: "🔵", name: "blue circle", category: "Symbols" },
  { emoji: "🟣", name: "purple circle", category: "Symbols" },
  { emoji: "⚫", name: "black circle", category: "Symbols" },
  { emoji: "⚪", name: "white circle", category: "Symbols" },
  { emoji: "🟥", name: "red square", category: "Symbols" },
  { emoji: "🟧", name: "orange square", category: "Symbols" },
  { emoji: "🟨", name: "yellow square", category: "Symbols" },
  { emoji: "🟩", name: "green square", category: "Symbols" },
  { emoji: "🟦", name: "blue square", category: "Symbols" },
  { emoji: "🟪", name: "purple square", category: "Symbols" },
  { emoji: "⬛", name: "black large square", category: "Symbols" },
  { emoji: "⬜", name: "white large square", category: "Symbols" },
  { emoji: "🔶", name: "large orange diamond", category: "Symbols" },
  { emoji: "🔷", name: "large blue diamond", category: "Symbols" },
  { emoji: "🔁", name: "repeat", category: "Symbols" },
  { emoji: "🔂", name: "repeat single", category: "Symbols" },
  { emoji: "▶️", name: "play button", category: "Symbols" },
  { emoji: "⏸️", name: "pause button", category: "Symbols" },
  { emoji: "⏹️", name: "stop button", category: "Symbols" },
  { emoji: "⏩", name: "fast forward", category: "Symbols" },
  { emoji: "⏪", name: "rewind", category: "Symbols" },
  { emoji: "🔀", name: "shuffle", category: "Symbols" },
  { emoji: "🔔", name: "bell", category: "Symbols" },
  { emoji: "🔕", name: "bell with slash", category: "Symbols" },
  { emoji: "🔊", name: "speaker high volume", category: "Symbols" },
  { emoji: "🔇", name: "muted speaker", category: "Symbols" },
  { emoji: "💧", name: "droplet", category: "Symbols" },
  { emoji: "🌐", name: "globe", category: "Symbols" },
  { emoji: "♻️", name: "recycling symbol", category: "Symbols" },
  { emoji: "💤", name: "zzz", category: "Symbols" },
  { emoji: "🏧", name: "atm sign", category: "Symbols" },
  { emoji: "♾️", name: "infinity", category: "Symbols" },
  { emoji: "💲", name: "heavy dollar sign", category: "Symbols" },
  { emoji: "💱", name: "currency exchange", category: "Symbols" },
  { emoji: "🔐", name: "locked with key", category: "Symbols" },
  { emoji: "🏳️", name: "white flag", category: "Symbols" },
  { emoji: "🏴", name: "black flag", category: "Symbols" },
  { emoji: "🇵🇭", name: "flag philippines", category: "Symbols" },
];
